# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
