# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180123_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
