# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 19:13
from __future__ import unicode_literals

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_donorprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, validators=[accounts.validators.validate_category]),
        ),
    ]
