# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 11:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=120)),
                ('date_of_event', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(blank=True, max_length=256, null=True, validators=[events.validators.validate_category])),
                ('slug', models.SlugField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
