# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_activation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
